### ISSUE TITLE
Tapping on UIBarButtonItems would be nice

### ISSUE THREAD

**Issue by gdean123** [jwfriese/Fleet#1]
What are the chances of getting the ability to tap on UIBarButtonItems? Perhaps something like this:

``` swift
extension UIBarButtonItem {
    func tap() {
        if self.target!.enabled! {
            self.target!.performSelector(self.action, withObject:self)
        }
    }
}
```

Or you could do something more extravagant like [PivotalCoreKit](https://github.com/pivotal/PivotalCoreKit/blob/7824469fdf975f78bcecf10ba8ba162dc3faf03c/UIKit/SpecHelper/Extensions/UIBarButtonItem%2BSpec.m)

**Comment by jwfriese** [comment]
I'll take a look at this now -- I see no reason it can't be there. Thanks for the suggestion George!

**Comment by jwfriese** [comment]
@gdean123 - This support has been added! You can find it in release 0.1.1

Thanks so much again for the suggestion! Please don't hesitate to continue making requests like this when you find yourself feeling pains writing tests for UIKit things 👍

**Comment by gdean123** [comment]
Fantastic! Thanks so much, Jared.
