### ISSUE TITLE
Support for UISwitch

### ISSUE THREAD

**Issue by palfvin** [jwfriese/Fleet#14]
It would be great to have the capability to do the equivalent of "tap" on a UISwitch like we can do on a UIButton.  Unfortunately, `sendActions(.touchUpInside)` doesn't seem to do anything as I would have expected it to.

**Comment by jwfriese** [comment]
@palfvin - Sorry for missing this issue for so long. I will start work on this as soon as I can. Here is the first story related to `UISwitch` support: 

https://www.pivotaltracker.com/story/show/136779675

**Comment by jwfriese** [comment]
Hi @palfvin,

I added this a bit back, and it finally is available in a proper release: [3.0.0](https://github.com/jwfriese/Fleet/releases/tag/3.0.0). 

Thanks again so much for all your feedback and contribution to Fleet!
