### ISSUE TITLE
selectRow helper not working properly with RxSwift/RxCocoa

### ISSUE THREAD

**Issue by palfvin** [jwfriese/Fleet#15]
When using selectRow with RxSwift/RxCocoa, selectRow acts like a no-op, apparently because RxSwift/RxCocoa does not implement willSelectRow and the default delegate behavior for that method is (oddly, at least during our unit test) to return `nil`.

**Comment by jwfriese** [comment]
@palfvin - Thanks for submitting this issue. I'll look into it right now and get back to you as soon as I can.

**Comment by jwfriese** [comment]
@palfvin - Thanks so much again for finding and reporting on this problem. You can find the fix for it in 2.1.0!

Let me know if you have any trouble.
