### ISSUE TITLE
Possible crash when calling UITextField.backspace()

### ISSUE THREAD

**Issue by wojciechczerski** [jwfriese/Fleet#19]
The implementation of the [`backspace()`](https://github.com/jwfriese/Fleet/blob/master/Fleet/CoreExtensions/Controls/TextInput/UITextField+Fleet.swift#L202) method contains a branch that calls the [`shouldChangeCharactersIn(...)`](https://github.com/jwfriese/Fleet/blob/master/Fleet/CoreExtensions/Controls/TextInput/UITextField+Fleet.swift#L215) on a `delegate` without checking beforehand, whether this optional method is implemented).

```swift
if existingText == "" {
    if let delegate = delegate {
        // this still gets called in this case
        let _ = delegate.textField!(self, shouldChangeCharactersIn: NSMakeRange(0, 0), replacementString: "")
    }

    return
}
```

Calling this method should be conditional and dependent on whether the delegate implements it. It has been done for other calls to `shouldChangeCharactersIn(...)`, for example:
```swift
let doesImplementShouldChangeText = delegate.responds(to: #selector(UITextFieldDelegate.textField(_:shouldChangeCharactersIn:replacementString:)))
var doesAllowTextChange = true
if doesImplementShouldChangeText {
    doesAllowTextChange = delegate.textField!(self, shouldChangeCharactersIn: NSMakeRange(location, backspaceAmount), replacementString: "")
}
```

**Comment by jwfriese** [comment]
@wojciechczerski - Thank you so much for raising this issue! I've updated `master` with the appropriate check in both the `UITextField` extension and the `UITextView` extension.

**Comment by jwfriese** [comment]
Release 4.2.0 has the code to solve for this. I will close this issue.
