### ISSUE TITLE
Would be nice to have UITextField.enterText

### ISSUE THREAD

**Issue by farshadtx** [jwfriese/Fleet#4]
It would be awesome if we could have the ability to enter text and trigger an editing changed control event. Instead of:

``` swift
subject.passwordField.text = "some-password"
subject.passwordField.sendActionsForControlEvents(UIControlEvents.EditingChanged)
```

I am imagining:

``` swift
subject.passwordField.enterText("some-password")
```

Perhaps it could also trigger EditingDidBegin and EditingDidEnd (or AllEditingEvents).

What do you think about this idea?

**Comment by jwfriese** [comment]
@farshadtx - Thanks for the suggestion! I've actually had it as an item on the Tracker board for a while:

https://www.pivotaltracker.com/story/show/114688831

I'll look into it.

**Comment by jwfriese** [comment]
@farshadtx - Take a look at version 0.1.4. It has support set up addressing most common test cases. 

As you might see in the Tracker story, there are still a couple things I wanted to do to make this feature really complete for all uses of UITextFields, but what I've included in 0.1.4 is a start. 

Let me know if you have any issues. I'll leave this open until all the tasks on that story are done.

**Comment by jgreubel** [comment]
It looks like your implementation of UITextField.enterText only works if there is a text field delegate (which we do not have). We are trying to do a drop-in replacement of

```
subject.passwordField.text = "some-password"
subject.passwordField.sendActionsForControlEvents(UIControlEvents.EditingChanged)
```

with

```
subject.passwordField.enterText("some-password")
```

but it doesn't seem to work.

**Comment by jwfriese** [comment]
@jgreubel - Thanks for this feedback. I'll work on this right away. Should be simple to fix 👍 

Tracker story here: 
https://www.pivotaltracker.com/story/show/114688831

**Comment by jwfriese** [comment]
@jgreubel - I've added the support requested. I'll include in another Fleet release after I add a couple more things!

Thanks so much again for the feedback :)
