### ISSUE TITLE
bindViewController does not give an error when attempting to bind a controller that is on another storyboard

### ISSUE THREAD

**Issue by jgreubel** [jwfriese/Fleet#5]
We were using bindViewController on a storyboard we newed up in test and were attempting to bind a viewController to it that was on another storyboard.  It didn't give an error eventhough we were supposed to use the correct function bindViewController: forReferencedStoryboardWithName

**Comment by jwfriese** [comment]
@jgreubel - Thanks for submitting this issue. The latest version (0.1.6) has better error messaging around the storyboard features as well as fully storyboard support for apps with a deployment target less than iOS 9 :)

I'll close this. Please reopen if you still aren't satisfied with the errors you get in this situation now.
