### ISSUE TITLE
Tapping on a AlertController Action does not dismiss the AlertController automatically 

### ISSUE THREAD

**Issue by jgreubel** [jwfriese/Fleet#7]
Using the .tapAlertActionWithTitle method does correctly call the callback I have set for the action being tapped, however it does not dismiss the UIAlertController automatically afterwards.  I assumed it would be dismissed since in my production code callback for that action I do not manually dismiss the alert controller and when I run the app, the alert controller is dismissed when I tap that action.  

What currently happens in test:

1) Execute code to cause AlertController to appear
-- Fleet.currentScreen()?.presentedAlert OR Fleet.currentScreen()?.topMostPresentedViewController both point at the UIAlertController correctly.

2) Use .tapAlertActionWithTitle on a title that exists
-- Fleet.currentScreen()?.presentedAlert OR Fleet.currentScreen()?.topMostPresentedViewController both **STILL** points at the same UIAlertController.

I expected this:
- Fleet.currentScreen()?.presentedAlert to be nil
- Fleet.currentScreen()?.topMostPresentedViewController to be the view controller that presented the alert

I am currently adding dismissViewControllerAnimated in the action callback (in the production code) to have this test work the way I expect.

**Comment by jwfriese** [comment]
@jgreubel - Thanks for filing this. I'll get to work at it soon. 

Here's the associated Tracker story: https://www.pivotaltracker.com/story/show/128850809

**Comment by jwfriese** [comment]
@jgreubel - I've added this functionality in 0.1.9. Let me know if there are any issues.
